services:
  # ================================
  # Redis - BullMQ Queue Management  
  # ================================
  redis:
    image: redis:7.2-alpine
    container_name: dam-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redispassword123
    volumes:
      - redis_data:/data
    networks:
      - dam-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # MinIO Object Storage
  # ================================
  minio:
    image: minio/minio:latest
    container_name: dam-minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    env_file:
      - ./.env
    volumes:
      - minio_data:/data
    networks:
      - dam-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # MinIO Client - Create Buckets
  # ================================
  minio-client:
    image: minio/mc:latest
    container_name: dam-minio-client
    depends_on:
      - minio
    networks:
      - dam-network
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb minio/dam-assets --ignore-existing;
      /usr/bin/mc policy set public minio/dam-assets;
      /usr/bin/mc admin info minio;
      exit 0;
      "

  # ================================
  # BullMQ Dashboard (Optional)
  # ================================
  bullmq-dashboard:
    image: deadly0/bull-board:latest
    container_name: dam-bullmq-dashboard
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    networks:
      - dam-network
    depends_on:
      - redis

  # ================================
  # The Backend Service
  # ================================
  server:
    container_name: digital_assets_management_server
    build:
      context: .
      dockerfile: packages/server/DockerFile.dev
    command: yarn workspace server dev
    ports:
      - "4000:4000"
    env_file:
      - ./.env
      
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dam-network
    depends_on:
      - redis
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/v1/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================================
  # Background Workers
  # ================================
  worker:
    container_name: digital_assets_management_worker
    build:
      context: .
      dockerfile: packages/server/DockerFile.worker
    command: yarn workspace server worker
    env_file:
      - ./.env
      
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dam-network
    depends_on:
      - redis
      - minio
      - server
    deploy:
      replicas: 1

  # ================================
  # The Frontend Service
  # ================================
  client:
    container_name: digital_assets_management_client
    build:
      context: .
      dockerfile: packages/client/DockerFile.dev
    command: yarn dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./packages/client:/app
      - /app/node_modules
    networks:
      - dam-network

# ================================
# Networks
# ================================
networks:
  dam-network:
    driver: bridge
    name: dam-network

# ================================
# Persistent Volumes
# ================================
volumes:
  redis_data:
    name: dam-redis-data
  minio_data:
    name: dam-minio-data